version: "3.8"
services:
  ai-server:
    build:
      context: .
      args:
        PRECACHE_CLIP: "1"   # 빌드 시 프리캐시 (0으로 끄기)
        PRECACHE_BLIP: "1"
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./data:/app/data            # examples/uploads
      - ./hf_cache:/opt/hf_cache    # 모델 캐시 영속화
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ai_db
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
