services:
  frontend:
    build:
      context: ./front-server
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL
      - VITE_TOSS_CLIENT_KEY
    ports:
      - "5173:5173"
    networks:
      - app-network

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE
      - SERVER_PORT
      - REDIS_HOST
      - REDIS_PORT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - STORAGE_S3_BUCKET
      - STORAGE_S3_REGION
      - STORAGE_S3_ENDPOINT
      - STORAGE_S3_PATH_STYLE
      - STORAGE_S3_PUBLIC_BASE_URL
      - STORAGE_S3_SECRETKEY
      - STORAGE_S3_ACCESSKEY
      - STORAGE_S3_ACL_PUBLIC_READ
      - SWEETTERACKER_API_KEY
      - COOLSMS_FROM_NUMBER
      - JWT_SECRET
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - COOLSMS_API_KEY
      - COOLSMS_API_SECRET
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_NAME
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE
      - SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_AUTHORIZATION_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_TOKEN_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_USER_INFO_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_AUTHORIZATION_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_TOKEN_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_INFO_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE
      - SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_AUTHORIZATION_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_TOKEN_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_INFO_URI
      - SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_NAME_ATTRIBUTE
      - SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_NAME_ATTRIBUTE
      - TOSS_CLIENT_KEY
      - TOSS_SECRET_KEY
    depends_on:
      - redis
    networks:
      - app-network

  ai-server:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      - API_SERVER_URL
      - FEEDBACK_CREATE_PATH
      - FEEDBACK_ELIGIBILITY_PATH
      - OPENAI_API_KEY
      - JWT_SECRET
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_URL
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - frontend
      - api-server
      - ai-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
