services:
  frontend:
    build:
      context: ./front-server
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL
      - VITE_TOSS_CLIENT_KEY
    ports:
      - "5173:5173"
    networks:
      - app-network

  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - STORAGE_S3_BUCKET=meonjeo
      - STORAGE_S3_REGION=kr-standard
      - STORAGE_S3_ENDPOINT=https://kr.object.ncloudstorage.com
      - STORAGE_S3_PATH_STYLE=true
      - STORAGE_S3_PUBLIC_BASE_URL=https://kr.object.ncloudstorage.com/meonjeo
      - STORAGE_S3_SECRETKEY=ncp_iam_BPKMKR63vHkWdL44Gqf404YiLu6LM71CdH
      - JWT_SECRET
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - redis
    networks:
      - app-network

  ai-server:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Seoul
      - API_SERVER_URL=http://api-server:8080
      - FEEDBACK_CREATE_PATH=/api/feedbacks
      - FEEDBACK_ELIGIBILITY_PATH=/api/feedbacks/eligibility
      - OPENAI_API_KEY
      - JWT_SECRET
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - DATABASE_URL
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - frontend
      - api-server
      - ai-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
