services:
  frontend:
    build:
      context: ./front-server
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL
      - VITE_TOSS_CLIENT_KEY
    ports:
      - "5173:5173"
    networks:
      - app-network

#  api-server:
#    build:
#      context: ./api-server
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - TZ=Asia/Seoul
#      - AWS_ACCESS_KEY_ID
#      - AWS_SECRET_ACCESS_KEY
#    networks:
#      - app-network
#
  ai-server:
    build:
      context: ./ai-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - DATABASE_URL
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_DB
      - JWT_SECRET
      - FEEDBACK_CREATE_PATH
      - FEEDBACK_ELIGIBILITY_PATH
      - API_SERVER_URL
      - OPENAI_API_KEY
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
