spring:
  datasource:
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: 'redis'
      port: 6379
  security:
    sms:
      cooldown-seconds: 60
      window10m-max: 3
      window24h-max: 10
      verify-max-attempts-hour: 5
      lock-minutes: 15
    oauth2:
      success:
        web-url: ${SPRING_SECURITY_OAUTH2_SUCCESS_WEB_URL}
        app-url: "ressol://oauth-success"
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [email, profile]
          kakao:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: [profile_nickname, profile_image]
            client-name: Kakao
          naver:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: [name, email, gender, birthday, birthyear, mobile]
            client-name: Naver
        provider:
          google:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_AUTHORIZATION_URI:https://accounts.google.com/o/oauth2/v2/auth}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_TOKEN_URI:https://oauth2.googleapis.com/token}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_GOOGLE_USER_INFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}
          kakao:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_AUTHORIZATION_URI:https://kauth.kakao.com/oauth/authorize}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_TOKEN_URI:https://kauth.kakao.com/oauth/token}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE:id}
          naver:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_AUTHORIZATION_URI:https://nid.naver.com/oauth2.0/authorize}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_TOKEN_URI:https://nid.naver.com/oauth2.0/token}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_INFO_URI:https://openapi.naver.com/v1/nid/me}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_NAME_ATTRIBUTE:response}

jwt:
  secret: ${JWT_SECRET}

COOLSMS_API_KEY: ${COOLSMS_API_KEY}
COOLSMS_API_SECRET: ${COOLSMS_API_SECRET}
COOLSMS_FROM_NUMBER: ${COOLSMS_FROM_NUMBER}

toss:
  secretKey: ${TOSS_SECRET_KEY}
  clientKey: ${TOSS_CLIENT_KEY}

sweettracker:
  api-key: ${SWEETTRACKER_API_KEY}

storage:
  s3:
    accessKey: ${STORAGE_S3_ACCESS_KEY:${STORAGE_S3_ACCESSKEY}}
    secretKey: ${STORAGE_S3_SECRET_KEY:${STORAGE_S3_SECRETKEY}}
