server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework

logging:
  level:
    com.meonjeo.meonjeo.chat: INFO
    org.springframework.messaging: INFO
    org.springframework.web.socket: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  # prod에서 secret 값을 자동 병합
  config:
    import: optional:file:./application-secret.yml

  datasource:
    # 캠퍼스 원격 DB를 기본값으로 사용 (ENV로 언제든 override)
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://project-db-campus.smhrd.com:3307/campus_25SW_FS_p3_1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:campus_25SW_FS_p3_1}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DB:0}

  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 40MB

  jackson:
    serialization:
      fail-on-empty-beans: false

storage:
  # 운영 기본은 s3, 자격증명 없으면 ENV로 STORAGE_MODE=local 지정해서 로컬 업로드 테스트 가능
  mode: ${STORAGE_MODE:s3}
  local:
    base-dir: ./uploads
  s3:
    bucket: ${STORAGE_S3_BUCKET}
    region: ${STORAGE_S3_REGION}
    endpoint: ${STORAGE_S3_ENDPOINT}
    path-style: ${STORAGE_S3_PATH_STYLE:true}
    public-base-url: ${STORAGE_S3_PUBLIC_BASE_URL}
    acl-public-read: ${STORAGE_S3_ACL_PUBLIC_READ:true}

phone:
  short-token:
    validity-seconds: 600
  code:
    ttl-seconds: 180
    max-attempts: 5

ai:
  # 오타 수정: http://http://... → http://
  base-url: ${AI_BASE_URL:http://ai-server:8000}
  timeout:
    connect-ms: 1500
    read-ms: 3000

# 단순 위임(ENV에서 주입)
COOLSMS_API_KEY: ${COOLSMS_API_KEY}
COOLSMS_API_SECRET: ${COOLSMS_API_SECRET}
COOLSMS_FROM_NUMBER: ${COOLSMS_FROM_NUMBER}

toss:
  successUrl: ${TOSS_SUCCESS_URL:http://hash-proj-v2.eba-ijnehrgn.ap-northeast-2.elasticbeanstalk.com/pay/success}
  failUrl: ${TOSS_FAIL_URL:http://hash-proj-v2.eba-ijnehrgn.ap-northeast-2.elasticbeanstalk.com/pay/fail}

sweettracker:
  api-key: ${SWEETTRACKER_API_KEY}
  base-url: https://info.sweettracker.co.kr
  timeout-ms: 3000
