server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Meonjeo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: Meonjeo
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false

phone:
  short-token:
    validity-seconds: 600        # 단기 토큰 유효시간(10분)
  code:
    ttl-seconds: 180             # 인증코드 유효시간(3분)
    max-attempts: 5

ai:
  base-url: http://localhost:8001
  timeout:
    connect-ms: 1500
    read-ms: 3000

COOLSMS_API_KEY: ${COOLSMS_API_KEY}
COOLSMS_API_SECRET: ${COOLSMS_API_SECRET}
COOLSMS_FROM_NUMBER: ${COOLSMS_FROM_NUMBER}