server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/campus_25SW_FS_p2_1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: campus_25SW_FS_p2_1
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 운영 시엔 validate 또는 none 권장
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    serialization:
      fail-on-empty-beans: false
