spring:
  datasource:
    password: smhrd1

  security:
    oauth2:
      success:
        web-url: "https://firsttry.smhrd.com/oauth-success"
        app-url: "firsttry://oauth-success"
      client:
        registration:
          google:
            client-id: 105804538661-bki9735poeh9lhb5ipifa76q1ehgf613.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "https://firsttry.smhrd.com/login/oauth2/code/google"
            scope: [email, profile]

          kakao:
            client-id: e32e080f64d51cfd48ff7b0a1510e9ac   # ← dev 값
            redirect-uri: "https://firsttry.smhrd.com/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: [profile_nickname, profile_image]       # ← dev 값
            client-name: Kakao

          naver:
            client-id: 64i0vgy3vEKOmGpvgjKO
            client-secret: N0GRBsOjxW
            redirect-uri: "https://firsttry.smhrd.com/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: [name, email, gender, birthday, birthyear, mobile]

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  secret: UqZ7E8G3DpA5OaWTdpFh4wYJmCtVzj9qTnVrpKmci8Ocf+8whKZQLqD1dZpgMq3W

COOLSMS_API_KEY: NCSUIY12KFF19TGV
COOLSMS_API_SECRET: NSEQ8WUKBXP4WCQHFZ2NJMJZGELJGGRW
COOLSMS_FROM_NUMBER: 01021049305

toss:
  secretKey: test_sk_Ba5PzR0ArnWKYzlMkdOx8vmYnNeD
  clientKey: test_ck_E92LAa5PVbl2qgY1lQeY87YmpXyJ

sweettracker:
  api-key: snWibz69uITfFcG1LevO5Q

storage:
  s3:
    accessKey: ncp_iam_BPAMKR1OCDPAEWFi55V1
    secretKey: ncp_iam_BPKMKR63vHkWdL44Gqf404YiLu6LM71CdH
